doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as Migrations classes should NOT be autoloaded
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: false
#    storage:
#        table_storage:
#            table_name: 'doctrine_migrations_versions'
#            version_column_name: 'version'
#            version_column_length: 1024
#            executed_at_column_name: 'executed_at'
