services:
  nginx:
    env_file:
      - ../.env
    image: nginx:1.27.4-alpine-slim
    container_name: ${NGINX_CONTAINER}
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ..:/var/www/symfony
    networks:
      - app_network
    depends_on:
      - php
  php:
    build:
      context: php
      args:
        - PHP_CONTAINER=${PHP_CONTAINER}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - PGID=${id -g}
        - PUID=${id -u}
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER}
    volumes:
      - ..:/var/www/symfony:rw
    networks:
      - app_network
    depends_on:
      - db
  db:
    image: mysql:lts
    container_name: ${DB_CONTAINER}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
